Repository cscodershub/Hacktoberfest-2021, pull requests merged in 2021-10, with the labels that each got.

#61 removed folders that were causing problems
  Cyber Security/Recon-Data/Goldman_Sachs/ayco.com/Jsscanner_results/js/-[ [32m200 [0m/raw.txt
  Cyber Security/Recon-Data/Goldman_Sachs/ayco.com/Jsscanner_results/js/-[ [36m [0m/raw.txt
Labels: bug, hacktoberfest-accepted, hacktober, hacktoberfest

#39 Dutch National Flag Algorithm
  Algorithms/C++/Dutch National Flag Algorithm/Algorithm
  Algorithms/C++/Dutch National Flag Algorithm/Readme.md
  Image Processing/Basics.ipynb
  Image Processing/lena.png
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#40 Added Recon Methodologies & Recon Data
  Cyber Security/Recon Methodology/Active Method/dns_bruteforcing.md
  Cyber Security/Recon Methodology/Active Method/js_scraping.md
  Cyber Security/Recon Methodology/Passive Enumeration/Certificate_logs.md
  Cyber Security/Recon Methodology/Passive Enumeration/Passive_Sources.md
  Cyber Security/Recon-Data/AT&T/subdomains.txt
  Cyber Security/Recon-Data/Paypal/subdomains.txt
  Cyber Security/Recon-Data/Quora/subdomains.txt
  Cyber Security/Recon-Data/TikTok/subdomains.txt
  Cyber Security/Recon-Data/Uber/subdomains.txt
  Cyber Security/Recon-Data/Youtube/subdomains.txt
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#43 Created reverseSinglyLinkedList.cpp
  Data-Structure/C++/reverseSinglyLinkedList.cpp
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#51 ➕ Added Sorting Algorithms code in CPP
  Data-Structure/C++/Cycle_Sort.cpp
  Data-Structure/C++/Insertion_Sort.cpp
  Data-Structure/C++/Selection_Sort.cpp
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#48 Sentimental Analysis of Stocks (NLP)
  NLP/Sentimental Analysis of Stocks.ipynb
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#50 added selection sort code file
  Data-Structure/C++/selectionsort_code.cpp
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#49 Add the famous Google NMT model
  NLP/neural_machine_translation.ipynb
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#54 Upload files
  Cyber Security/WebShells/529.php
  Cyber Security/WebShells/CrystalShell v.1.php
  Cyber Security/WebShells/PHPShell-encoded.php
  Cyber Security/WebShells/c99shell.php
  Cyber Security/Web_Application_Pentesting/SQLi/Payloads.txt
  Cyber Security/Web_Application_Pentesting/XSS/Payloads.txt
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#58 Created KahnAlgo.java
  Algorithms/Java/KahnAlgo.java
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#62 some file added
  Data-Structure/C++/circular linked list.cpp
  Data-Structure/C++/doubly linked list.cpp
  Data-Structure/C/AVL Tree.c
  Data-Structure/C/Binay Search Tree.c
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#53 Subset Sum dynamic programming question
  Data-Structure/C++/subsetsum.cpp
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#59 added some string questions
  Data-Structure/C++/1_Find the Difference.cpp
  Data-Structure/C++/2_ Reformat Date.cpp
  Data-Structure/C++/3_Largest Number.cpp
  Data-Structure/C++/4_Longest Palindromic Substring.cpp
  Data-Structure/C++/5_ZigZag Conversion.cpp
  Data-Structure/C++/6_Integer to Roman.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#68 Url shortener
  Beginners Project/url-shortener/Client/.env
  Beginners Project/url-shortener/Client/.gitignore
  Beginners Project/url-shortener/Client/README.md
  Beginners Project/url-shortener/Client/package-lock.json
  Beginners Project/url-shortener/Client/package.json
  Beginners Project/url-shortener/Client/public/favicon.ico
  Beginners Project/url-shortener/Client/public/index.html
  Beginners Project/url-shortener/Client/public/logo192.png
  Beginners Project/url-shortener/Client/public/logo512.png
  Beginners Project/url-shortener/Client/public/manifest.json
  Beginners Project/url-shortener/Client/public/robots.txt
  Beginners Project/url-shortener/Client/src/App.css
  Beginners Project/url-shortener/Client/src/App.js
  Beginners Project/url-shortener/Client/src/index.css
  Beginners Project/url-shortener/Client/src/index.js
  Beginners Project/url-shortener/Client/src/reportWebVitals.js
  Beginners Project/url-shortener/README.md
  Beginners Project/url-shortener/Server/db/db.js
  Beginners Project/url-shortener/Server/public/html/index.html
  Beginners Project/url-shortener/Server/server.js
  Beginners Project/url-shortener/Server/src/controller/geturl.js
  Beginners Project/url-shortener/Server/src/controller/posturl.js
  Beginners Project/url-shortener/Server/src/models/url.js
  Beginners Project/url-shortener/Server/src/router/url.js
  Beginners Project/url-shortener/package-lock.json
  Beginners Project/url-shortener/package.json
Labels: enhancement, hacktoberfest-accepted, hacktober, hacktoberfest

#70 Rename widget.js? to widget.js
  Cyber Security/Recon-Data/yummly.com/Jsscanner_results/db/www.yummly.com-https/widget.js
Labels: bug, enhancement, good first issue, hacktoberfest-accepted, hacktober, hacktoberfest

#67 Simple contour generator using Open CV
  Algorithms/Python/Spam_detection.py
  Image Processing/Contour_generation.py
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#72 Added codebase for LinkedIn Auto connection
  Beginners Project/linkedin auto connect/autoconnect.py
  Beginners Project/linkedin auto connect/connectbut.png
  Beginners Project/linkedin auto connect/notebut.png
  Beginners Project/linkedin auto connect/readme.md
  Beginners Project/linkedin auto connect/sendbut.png
Labels: enhancement, hacktoberfest-accepted, hacktober, hacktoberfest

#88 Create androidflutter readme.md
  Android/androidflutter readme.md
Labels: hacktoberfest-accepted, hacktober, hacktoberfest

#63 Graph implementation using edge pairs
  Data-Structure/C++/Graph_Edge_Pairs.cpp
Labels: hacktoberfest-accepted, hacktober, hacktoberfest
